kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: spotlight
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: spotlight
  apiGroup: rbac.authorization.k8s.io