name: Docker Image CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: feature
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker FE image
      run: docker build fe --file fe/Dockerfile --tag spotlight-fe  --tag latest

    - name: Build the Docker BE image
      run: docker build server/src --file server/src/Dockerfile --tag spotlight-be  --tag latest

    - name: Configure AWS Credentials
      run:
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.NONPROD_ROLE_ARN }}
          role-duration-seconds: 3600

    - name: Login to Amazon ECR
      run:
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Variables
      run: |
          FEATURE_ID=$(echo -n ${{ github.ref }} | sed 's/.*\///g' | tr . - | tr '[:upper:]' '[:lower:]')
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2)
          RELEASE_NAME="${FEATURE_ID}--${PROJECT_NAME}"
          BASE_ENDPOINT=https://${RELEASE_NAME}.${ENVIRONMENT_NAME}.chgapi.net
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          echo "FEATURE_ID=$FEATURE_ID" >> $GITHUB_ENV
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "BASE_ENDPOINT=$BASE_ENDPOINT" >> $GITHUB_ENV
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
    - name: Create ECR Repository
      run: |
          aws ecr create-repository --repository-name ${{ env.PROJECT_NAME }} || echo 'repository already created'

    - name: Wait For Repo to Exist
      timeout-minutes: 2
      run: |
          while ! aws ecr describe-repositories --repository-names ${{ env.PROJECT_NAME }} > /dev/null; do sleep 5; done

    - name: Build, Tag, and Push Image to Amazon ECR
      run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }} . --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ env.ECR_REGISTRY }}
