name: Docker Image CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker FE image
      run: docker build fe --file Dockerfile --tag spotlight-FE  --tag latest
    - name: Build the Docker BE image
      run: docker build server/src --file Dockerfile --tag spotlight-BE  -tag latest